# Generated by Django 3.2.7 on 2021-11-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio de Venta'),
        ),
    ]
