# Generated by Django 3.2.7 on 2021-11-27 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20211101_1556'),
        ('menu', '0003_menuitem_sell_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuProduct',
            fields=[
                ('menuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.menuitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_products', to='product.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Menú Producto',
                'verbose_name_plural': 'Menú  Producto',
            },
            bases=('menu.menuitem',),
        ),
    ]
