# Generated by Django 3.2.7 on 2021-11-27 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipedetail'),
        ('menu', '0004_menuproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuRecipe',
            fields=[
                ('menuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.menuitem')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_recipe', to='recipe.recipe', verbose_name='Receta')),
            ],
            options={
                'verbose_name': 'Menú Receta',
                'verbose_name_plural': 'Menú  Receta',
            },
            bases=('menu.menuitem',),
        ),
    ]
