# Generated by Django 3.2.7 on 2021-12-13 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipedetail'),
        ('product', '0007_auto_20211201_1752'),
        ('menu', '0005_menurecipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu_products', to='product.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='menurecipe',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu_recipe', to='recipe.recipe', verbose_name='Receta'),
        ),
    ]
