# Generated by Django 3.2.7 on 2021-12-13 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_warehousemovement_options'),
        ('menu', '0006_auto_20211212_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='warehouse',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.warehouse', verbose_name='Almacen'),
        ),
    ]
