# Generated by Django 3.2.7 on 2022-02-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_menuitem_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='menurecipe',
            name='daily_quantity',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
    ]
