# Generated by Django 3.2.7 on 2021-10-05 21:31

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Nombre')),
                ('address', models.CharField(blank=True, max_length=360, null=True, verbose_name='Dirección')),
                ('ruc', models.CharField(blank=True, max_length=13, null=True, verbose_name='RUC')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='restaurant/', verbose_name='Figura')),
                ('state', models.CharField(blank=True, choices=0, default=[(0, 'Activo'), (1, 'Inactivo')], max_length=10, verbose_name='Estado')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electronico')),
                ('business_name', models.CharField(blank=True, max_length=160, null=True, verbose_name='Razón Social')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Telefono')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurante',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.restaurant', verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
