# Generated by Django 3.2.7 on 2021-10-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='state',
            field=models.CharField(blank=True, choices=[(0, 'Activo'), (1, 'Inactivo')], default=0, max_length=10, verbose_name='Estado'),
        ),
    ]
