# Generated by Django 3.2.7 on 2021-10-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_restaurant_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role_name',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('role_name', 'restaurant'), name='unique_rol_name'),
        ),
    ]
