# Generated by Django 3.2.7 on 2022-01-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_restaurant_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'Activo'), (1, 'Inactivo')], default=0, verbose_name='Estado'),
        ),
    ]
