# Generated by Django 3.2.7 on 2022-09-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_restaurant_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='igv_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.18, max_digits=8, verbose_name='% IGV'),
        ),
    ]
