# Generated by Django 3.2.7 on 2026-04-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_restaurant_igv_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='igv_percent',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.18, max_digits=8, verbose_name='% IGV'),
        ),
    ]
