# Generated by Django 3.2.7 on 2021-11-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gross_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Peso Bruto'),
        ),
        migrations.AddField(
            model_name='product',
            name='net_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Peso Neto'),
        ),
        migrations.AddField(
            model_name='product',
            name='yield_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Porcentaje de Rendimiento'),
        ),
    ]
