# Generated by Django 3.2.7 on 2021-12-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20211101_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gross_weight',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Peso Bruto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='net_weight',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Peso Neto'),
        ),
    ]
