# Generated by Django 3.2.7 on 2021-11-13 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20211005_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall', to='accounts.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Salones',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre')),
                ('capacity', models.IntegerField(default=0, verbose_name='Capacidad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='hall.hall', verbose_name='Salón')),
            ],
            options={
                'verbose_name': 'Mesas',
            },
        ),
    ]
