# Generated by Django 3.2.7 on 2021-11-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='state',
            field=models.IntegerField(choices=[(0, 'Libre'), (1, 'Ocupado'), (2, 'Por desocuparse'), (3, 'Reservado')], default=0, verbose_name='Estado'),
        ),
    ]
