# Generated by Django 3.2.7 on 2021-11-13 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0002_table_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hall',
            options={'verbose_name': 'Salón', 'verbose_name_plural': 'Salones'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'Mesa', 'verbose_name_plural': 'Mesas'},
        ),
    ]
