# Generated by Django 3.2.7 on 2021-10-14 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20211005_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('symbol', models.CharField(max_length=10, verbose_name='Simbolo')),
                ('is_active', models.BooleanField(default=True, null=True, verbose_name='Activo')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='accounts.restaurant', verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': ('Tipo de Moneda',),
                'verbose_name_plural': 'Tipos de Moneda',
            },
        ),
    ]
