# Generated by Django 3.2.7 on 2021-10-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='code',
            field=models.CharField(default='', max_length=10, verbose_name='Código'),
        ),
    ]
