# Generated by Django 3.2.7 on 2022-01-12 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_restaurant_state'),
        ('document_type', '0003_rename_codigo_documenttype_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('document', models.CharField(default=None, max_length=25, null=True, verbose_name='Documento')),
                ('phone', models.CharField(default=None, max_length=20, null=True, verbose_name='Telefóno')),
                ('address', models.CharField(default=None, max_length=250, null=True, verbose_name='Dirección')),
                ('document_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='clients', to='document_type.documenttype', verbose_name='Tipo de Documento')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='accounts.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
