# Generated by Django 3.2.7 on 2023-07-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='client',
            name='document',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Telefóno'),
        ),
    ]
