# Generated by Django 3.2.7 on 2021-10-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_type', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='codigo',
            field=models.CharField(max_length=25, null=True, verbose_name='Código'),
        ),
    ]
