# Generated by Django 3.2.7 on 2021-10-07 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_type', '0002_documenttype_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documenttype',
            old_name='codigo',
            new_name='code',
        ),
    ]
