# Generated by Django 3.2.7 on 2021-10-14 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20211005_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('address', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Dirección')),
                ('is_main', models.BooleanField(default=False, verbose_name='Almacen Principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='accounts.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Almacen',
                'verbose_name_plural': 'Alamacenes',
            },
        ),
    ]
