# Generated by Django 3.2.7 on 2021-10-14 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_warehousemovement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehousemovement',
            options={'verbose_name': 'Movimiento de Almacen', 'verbose_name_plural': 'Movimientos de Almacen'},
        ),
    ]
