# Generated by Django 3.2.7 on 2021-10-07 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20211005_2130'),
        ('document_type', '0003_rename_codigo_documenttype_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('document', models.CharField(max_length=25, verbose_name='Documento')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='Telefóno')),
                ('address', models.CharField(max_length=250, null=True, verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='providers', to='document_type.documenttype', verbose_name='Tipo de Documento')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='accounts.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
