# Generated by Django 3.2.7 on 2021-10-14 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_currency_code'),
        ('accounts', '0003_auto_20211005_2130'),
        ('product', '0005_alter_product_brand'),
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrizingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='prices', to='currency.currency', verbose_name='Tipo de Moneda')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='prices', to='product.product', verbose_name='Producto')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='prices', to='provider.provider', verbose_name='Proveedor')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='accounts.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Precio',
                'verbose_name_plural': 'Tabla de Precios',
            },
        ),
    ]
