# Generated by Django 3.2.7 on 2021-10-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_prizingtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizingtable',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo'),
        ),
    ]
