# Generated by Django 3.2.7 on 2021-12-01 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document_type', '0003_rename_codigo_documenttype_code'),
        ('provider', '0003_prizingtable_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='address',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='document',
            field=models.CharField(default=None, max_length=25, null=True, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='document_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='providers', to='document_type.documenttype', verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='Telefóno'),
        ),
    ]
