# Generated by Django 3.2.7 on 2021-10-22 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0005_operationsdetail_purchasedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Monto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='operations.operation', verbose_name='Operación')),
            ],
        ),
    ]
