# Generated by Django 3.2.7 on 2021-11-01 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20211101_1556'),
        ('recipe', '0003_alter_recipe_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Cantidad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes_details', to='product.product', verbose_name='Producto')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='recipe.recipe', verbose_name='Receta')),
            ],
            options={
                'verbose_name': 'Detalle de Receta',
                'verbose_name_plural': 'Detalles de Receta',
            },
        ),
    ]
