# Generated by Django 3.2.7 on 2022-01-10 21:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_restaurant_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_sol', models.CharField(default='', max_length=20, verbose_name='Usuario SOL')),
                ('password_sol', models.CharField(default='', max_length=30, verbose_name='Clave SOL')),
                ('sunat_certificate', models.FileField(default=None, null=True, upload_to='sunat/certificates.p12', validators=[django.core.validators.FileExtensionValidator(['p12'])], verbose_name='Certificado SUNAT')),
                ('password_certificate', models.CharField(default=None, max_length=50, null=True, verbose_name='Contraseña del Certificado')),
                ('certificate_pem', models.FileField(blank=True, null=True, upload_to='sunat/certificates.pem', verbose_name='Certificado PEM')),
                ('certificate_private_key', models.FileField(blank=True, null=True, upload_to='sunat/certificates.keys', verbose_name='Clave Privada de Certificado')),
                ('sunat_name', models.CharField(default='', max_length=500, verbose_name='Nombre en SUNAT')),
                ('location_code', models.CharField(default='0000', max_length=10, verbose_name='Código Ubigeo')),
                ('second_user', models.CharField(default='', max_length=10, verbose_name='Segundo Usuario SOL')),
                ('second_user_password', models.CharField(default='', max_length=10, verbose_name='Contraseña Segundo Usuario SOL')),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_settings', to='accounts.restaurant', verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': 'Configuración de Facturación',
                'verbose_name_plural': 'Configuraciones de Facturación',
            },
        ),
    ]
