# Generated by Django 3.2.7 on 2022-01-16 03:49

import apps.bill.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_file', models.FileField(blank=True, default=None, storage=apps.bill.storage.OverwriteStorage, upload_to='sunat/bill.xml/')),
                ('zip_file', models.FileField(blank=True, default=None, storage=apps.bill.storage.OverwriteStorage, upload_to='sunat/bill.zip/')),
                ('response_zip_file', models.FileField(blank=True, default=None, storage=apps.bill.storage.OverwriteStorage, upload_to='sunat/response.bill.zip/')),
                ('send_file', models.FileField(blank=True, default=None, storage=apps.bill.storage.OverwriteStorage, upload_to='sunat/bill.send/')),
                ('issue_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
