# Generated by Django 3.2.7 on 2022-01-16 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0020_order_client'),
        ('bill', '0002_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOrder',
            fields=[
                ('bill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bill.bill')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operations.order', verbose_name='Pedido')),
            ],
            bases=('bill.bill',),
        ),
    ]
