# Generated by Django 3.2.7 on 2022-01-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_billorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingsetting',
            name='second_user_password',
            field=models.CharField(default='', max_length=100, verbose_name='Contraseña Segundo Usuario SOL'),
        ),
    ]
