# Generated by Django 3.2.7 on 2022-09-09 16:43

import apps.bill.models
import apps.bill.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_alter_billingsetting_second_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='response_code',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='bill',
            name='response_xml_file',
            field=models.FileField(blank=True, default=None, storage=apps.bill.storage.OverwriteStorage, upload_to=apps.bill.models.Bill.response_xml_file_upload_location),
        ),
        migrations.AlterField(
            model_name='bill',
            name='response_zip_file',
            field=models.FileField(blank=True, default=None, storage=apps.bill.storage.OverwriteStorage, upload_to=apps.bill.models.Bill.response_zip_file_upload_location),
        ),
        migrations.AlterField(
            model_name='bill',
            name='send_file',
            field=models.FileField(blank=True, default=None, storage=apps.bill.storage.OverwriteStorage, upload_to=apps.bill.models.Bill.send_file_upload_location),
        ),
    ]
