# Generated by Django 3.2.7 on 2022-09-24 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0025_auto_20220924_0207'),
        ('bill', '0005_auto_20220909_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillReturnedOrder',
            fields=[
                ('bill_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bill.bill')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operations.returnedorder', verbose_name='Pedido Devuelto')),
            ],
            bases=('bill.bill',),
        ),
    ]
