# Generated by Django 3.2.7 on 2021-10-19 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211005_2130'),
        ('currency', '0002_currency_code'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='SubTotal')),
                ('serie', models.CharField(blank=True, max_length=10, null=True, verbose_name='Serie')),
                ('correlative', models.IntegerField(default=0, null=True, verbose_name='Correlativo')),
                ('issue_date', models.DateField(verbose_name='Fecha')),
                ('igv', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='IGV')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='currency.currency', verbose_name='Tipo de moneda')),
                ('payment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.paymenttype', verbose_name='Tipo de Pago')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='accounts.restaurant', verbose_name='Restaurante')),
            ],
        ),
    ]
