# Generated by Django 3.2.7 on 2021-10-20 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_operation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'verbose_name': 'Operación', 'verbose_name_plural': 'Operaciones'},
        ),
    ]
