# Generated by Django 3.2.7 on 2021-10-20 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_prizingtable_cost'),
        ('operations', '0003_alter_operation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.operation')),
                ('provider', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='provider.provider', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
            bases=('operations.operation',),
        ),
    ]
