# Generated by Django 3.2.7 on 2021-10-20 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_warehousemovement_options'),
        ('operations', '0004_auto_20211019_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Sub Total')),
                ('unitary_value', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Valor Unitario')),
                ('igv', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='IGV')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_operation', to='warehouse.warehousemovement', verbose_name='Movimiento')),
                ('operation', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='operations.operation', verbose_name='Operation')),
            ],
            options={
                'verbose_name': 'Detalle de Operacion',
            },
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('operationsdetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operations.operationsdetail')),
            ],
            bases=('operations.operationsdetail',),
        ),
    ]
