# Generated by Django 3.2.7 on 2021-11-02 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_warehousemovement_options'),
        ('operations', '0005_operationsdetail_purchasedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationsdetail',
            name='movement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail_operation', to='warehouse.warehousemovement', verbose_name='Movimiento'),
        ),
    ]
