# Generated by Django 3.2.7 on 2021-11-28 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_warehousemovement_options'),
        ('menu', '0005_menurecipe'),
        ('operations', '0007_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cantidad')),
                ('state', models.IntegerField(choices=[(0, 'Preparando'), (1, 'Entregado')], verbose_name='Estado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='operations.order', verbose_name='Cabecera')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='menu.menuitem', verbose_name='Item de Menú')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_details', to='warehouse.warehouse', verbose_name='Almacen')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedido',
            },
        ),
    ]
