# Generated by Django 3.2.7 on 2021-11-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_warehousemovement_options'),
        ('operations', '0008_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='movements',
            field=models.ManyToManyField(related_name='order_details', to='warehouse.WarehouseMovement'),
        ),
    ]
