# Generated by Django 3.2.7 on 2021-12-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_orderdetail_movements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Precio Unitario'),
        ),
    ]
