# Generated by Django 3.2.7 on 2021-12-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_auto_20211214_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_datetime',
            field=models.DateTimeField(default=None, null=True, verbose_name='Hora de Fin'),
        ),
    ]
