# Generated by Django 3.2.7 on 2022-01-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_alter_order_end_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='state',
            field=models.IntegerField(choices=[(0, 'Preparando'), (1, 'Entregado'), (2, 'En Cola')], verbose_name='Estado'),
        ),
    ]
