# Generated by Django 3.2.7 on 2022-01-09 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_restaurant_state'),
        ('operations', '0012_alter_orderdetail_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('payment_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.paymenttype', verbose_name='Tipo de Pago')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_documents', to='accounts.restaurant', verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': 'Documento de Pago',
                'verbose_name_plural': 'Documento de Pago',
            },
        ),
    ]
