# Generated by Django 3.2.7 on 2022-01-09 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_paymentdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='payment_document',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.paymentdocument', verbose_name='Documento de Pago'),
        ),
    ]
