# Generated by Django 3.2.7 on 2022-01-09 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_operation_payment_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdocument',
            name='payment_type',
        ),
    ]
