# Generated by Django 3.2.7 on 2022-01-09 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_currency_code'),
        ('operations', '0015_remove_paymentdocument_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='correlative',
            field=models.IntegerField(default=0, null=True, verbose_name='Correlativo'),
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='currency.currency', verbose_name='Tipo de moneda'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_document',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.paymentdocument', verbose_name='Documento de Pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.paymenttype', verbose_name='Tipo de Pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='serie',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Serie'),
        ),
    ]
