# Generated by Django 3.2.7 on 2022-01-11 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0016_auto_20220109_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Código')),
                ('correlative', models.IntegerField(default=1, verbose_name='Correlativo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('payment_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.paymentdocument', verbose_name='Documento de Pago')),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Series',
            },
        ),
    ]
