# Generated by Django 3.2.7 on 2022-01-11 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_serie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Serie',
        ),
    ]
