# Generated by Django 3.2.7 on 2022-01-13 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_is_active'),
        ('operations', '0019_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Cliente'),
        ),
    ]
