# Generated by Django 3.2.7 on 2022-02-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0020_order_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdocument',
            name='electronic_document',
            field=models.IntegerField(choices=[(0, 'Factura Electrónica')], default=None, null=True, verbose_name='Documento Electrónico'),
        ),
    ]
