# Generated by Django 3.2.7 on 2022-02-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0021_paymentdocument_electronic_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdocument',
            name='electronic_document',
            field=models.IntegerField(choices=[(0, 'Factura Electrónica'), (1, 'Nota de Pedido')], default=None, null=True, verbose_name='Documento Electrónico'),
        ),
    ]
