# Generated by Django 3.2.7 on 2022-09-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0022_alter_paymentdocument_electronic_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='igv_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.18, max_digits=8, verbose_name='% IGV'),
        ),
        migrations.AddField(
            model_name='paymentdocument',
            name='cancel_sale',
            field=models.BooleanField(default=False, verbose_name='Cancela venta'),
        ),
        migrations.AddField(
            model_name='paymentdocument',
            name='is_cancelable',
            field=models.BooleanField(default=False, verbose_name='Cancelable'),
        ),
        migrations.AddField(
            model_name='paymentdocument',
            name='require_serie',
            field=models.BooleanField(default=False, verbose_name='Requiere serie'),
        ),
        migrations.AlterField(
            model_name='paymentdocument',
            name='electronic_document',
            field=models.IntegerField(choices=[(0, 'No Definido'), (1, 'Factura Electrónica'), (3, 'Boleta de Venta'), (7, 'Nota de Crédito')], default=None, null=True, verbose_name='Documento Electrónico'),
        ),
    ]
