# Generated by Django 3.2.7 on 2022-09-13 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0023_auto_20220908_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='related_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.order'),
        ),
    ]
