# Generated by Django 3.2.7 on 2022-09-24 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_restaurant_igv_percent'),
        ('operations', '0024_order_related_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='related_order',
        ),
        migrations.CreateModel(
            name='ReturnedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Serie')),
                ('correlative', models.IntegerField(default=0, null=True, verbose_name='Correlativo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('payment_document', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.paymentdocument', verbose_name='Documento de Pago')),
                ('payment_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.paymenttype', verbose_name='Tipo de Pago')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.order')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_orders', to='accounts.restaurant', verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': 'Pedido Devuelto',
                'verbose_name_plural': 'Pedidos Devueltos',
            },
        ),
    ]
