# Generated by Django 3.2.7 on 2022-09-24 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0025_auto_20220924_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnedorder',
            name='payment_type',
        ),
    ]
