# Generated by Django 3.2.7 on 2022-09-24 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0026_remove_returnedorder_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnedorder',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hora'),
            preserve_default=False,
        ),
    ]
