# Generated by Django 3.2.7 on 2022-10-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0027_returnedorder_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Hora de Fin'),
        ),
    ]
