# Generated by Django 3.2.7 on 2026-04-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0028_alter_order_end_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='igv',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='IGV'),
        ),
        migrations.AlterField(
            model_name='order',
            name='igv_percent',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.18, max_digits=8, verbose_name='% IGV'),
        ),
    ]
