# Generated by Django 3.2.7 on 2026-04-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0029_auto_20260409_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Comentario'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_delivery',
            field=models.BooleanField(default=False, verbose_name='Delibery'),
        ),
    ]
